Improve CodeblocksOverFileUpload handler and refactor DirectoryUtils
codesupport/discord-bot pull request #83
Opened 2020-07-12 22:04 UTC by ajsaraujo

Resolves #78, resolves #79

2020-07-12 22:06 UTC, ajsaraujo commented on src/event/handlers/CodeblocksOverFileUploadsHandler.ts
> +					invalidFileExtension = fileExtension;
This assumes that only one file attachment can be sent per message, although we have a map of attachments... Anyway, I didn't find a way of sending a message with more than one file attachment yet.

2020-07-12 22:09 UTC, ajsaraujo commented on test/event/handlers/CodeblocksOverFileUploadsHandlerTest.ts
>  			message.attachments.set("720390958847361064", new MessageAttachment("720390958847361064", "test.png"));
I thought that maybe we could have that string as a constant at the top of the file?

2020-07-25 23:09 UTC, LamboCreeper requested changes

2020-07-25 23:09 UTC, LamboCreeper commented on src/utils/DirectoryUtils.ts
> +        /* eslint-enable */
Formatting seems a bit off.

2020-07-25 23:09 UTC, LamboCreeper commented on src/utils/DirectoryUtils.ts
> +    private static require = require;
Would like a blank line between these since they're sperate.

2020-07-25 23:09 UTC, LamboCreeper commented on test/utils/DirectoryUtilsTest.ts
> +	});
Seems pointless?

2020-07-25 23:30 UTC, ajsaraujo commented on src/utils/DirectoryUtils.ts
> +    }
The linter complains: `Expected indentation of 5 tabs, found 8 spaces`. 
However it's rendering fine here and on my editor. If I try to quick fix it I still get `Mixed indentation of tabs and spaces`, which renders awfully.

2020-07-25 23:52 UTC, ajsaraujo commented on src/utils/DirectoryUtils.ts
> +    }
I disabled the linter for that part of the code. :p

2020-07-26 11:53 UTC, LamboCreeper approved these changes

2020-07-27 15:03 UTC, merged